 
CREATE DATABASE IF NOT EXISTS bank_sample
USE bank_sample;
--user
CREATE TABLE IF NOT EXISTS user (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(50) NOT NULL ,
  MOBILE_NO int(10) NOT NULL,
  ACCOUNT_NO int(10) NOT NULL,
  PRIMARY KEY (USER_ID)
) 


--funds
CREATE TABLE IF NOT EXISTS funds (
  FUNDS_ID int(11) NOT NULL AUTO_INCREMENT,
  BALANCE double NOT NULL,
  USER_ID int(11) NOT NULL,
  PRIMARY KEY (FUNDS_ID),
  KEY Fund_user_Fk (USER_ID),
  CONSTRAINT Fund_user_Fk FOREIGN KEY (USER_ID) REFERENCES user (USER_ID)
)

--user_login
CREATE TABLE IF NOT EXISTS user_login (
  LOGIN_ID int(11) NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(50) NOT NULL,
  USER_ID int(11) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  PRIMARY KEY (LOGIN_ID),
  KEY FK_user_login_user (USER_ID),
  CONSTRAINT FK_user_login_user FOREIGN KEY (USER_ID) REFERENCES user (USER_ID)
)
